### ISSUE TITLE
drbd-reactor fails with error when listening on 127.0.0.1

### ISSUE THREAD

**Issue by kvaps** [LINBIT/drbd-reactor#5]
config:
```toml
[[prometheus]]
address = "127.0.0.1:9942"
enums = true
```
logs:
```
INFO [drbd_reactor::plugin::prometheus] tcp_handler: error in stream, most likely harmless shutdown
```
